import type { Component } from 'vue'

export type LabLoader = () => Promise<{ default: Component }>

/** Auto-generated by ci/register-plugins.py */
export const LAB_PANEL_LOADERS: Record<string, LabLoader> = {
  'edu.hot.mock': () => import('@core/examples/plugins/mock/frontend/MockLab.vue'),
  'edu.cn.gov.bid-graph': () => import('@gov/plugins/frontend/BidGraphLab.vue'),
  'edu.cn.gov.multisig': () => import('@gov/plugins/frontend/MultisigLab.vue'),
  'edu.cn.gov.supply': () => import('@gov/plugins/frontend/SupplyLab.vue'),
  'edu.global.sandbox.election': () => import('@sandbox/plugins/frontend/election/ElectionLab.vue'),
  'edu.global.sandbox.logistics': () => import('@sandbox/plugins/frontend/logistics/LogisticsLab.vue'),
  'edu.global.sandbox.regulatory': () => import('@sandbox/plugins/frontend/regulatory/RegulatoryLab.vue'),
  'edu.global.sandbox.religion': () => import('@sandbox/plugins/frontend/religion/ReligionLab.vue'),
  'edu.global.sandbox.welfare': () => import('@sandbox/plugins/frontend/welfare/WelfareLab.vue'),
  'edu.cn.trace.charity': () => import('@trace/plugins/charity-ledger/frontend/CharityLedgerLab.vue'),
  'edu.cn.trace.food': () => import('@trace/plugins/food-trace/frontend/FoodTraceLab.vue'),
  'edu.cn.trace.medical': () => import('@trace/plugins/medical-tamper/frontend/MedicalTamperLab.vue'),
  'edu.hot.aa-session': () => import('@hot-labs/plugins/aa-session/frontend/HotLab.vue'),
  'edu.hot.aa-wallet': () => import('@hot-labs/plugins/aa-wallet/frontend/HotLab.vue'),
  'edu.hot.ai-agent': () => import('@hot-labs/plugins/ai-agent/frontend/HotLab.vue'),
  'edu.hot.dao': () => import('@hot-labs/plugins/dao/frontend/HotLab.vue'),
  'edu.hot.depin': () => import('@hot-labs/plugins/depin/frontend/HotLab.vue'),
  'edu.hot.did': () => import('@hot-labs/plugins/did/frontend/HotLab.vue'),
  'edu.hot.language-advisor': () => import('@hot-labs/plugins/frontend/LanguageAdvisorLab.vue'),
  'edu.hot.mev': () => import('@hot-labs/plugins/mev/frontend/HotLab.vue'),
  'edu.hot.rwa-edu': () => import('@hot-labs/plugins/rwa-edu/frontend/HotLab.vue'),
  'edu.hot.zk-circuit': () => import('@hot-labs/plugins/zk-circuit/frontend/HotLab.vue'),
  'edu.hot.zk-modular': () => import('@hot-labs/plugins/zk-modular/frontend/HotLab.vue'),
}

export function resolveLabLoader(pluginId: string): LabLoader | null {
  return LAB_PANEL_LOADERS[pluginId] ?? null
}
