#!/usr/bin/env python3
"""Scan sub-repo plugin.manifest.yaml files; generate registry + lab-loaders."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

GROUP_MAP = {
    "hot_topic": "Web3 热点",
    "cn_domain": "国内领域",
    "global_sandbox": "海外沙箱",
}

REPO_ALIAS = {
    "web3-hot-topic-labs": "@hot-labs",
    "supervision-trace-edu-suite": "@trace",
    "enterprise-gov-edu-demo": "@gov",
    "global-social-edu-sandbox": "@sandbox",
    "web3-edu-platform-core": "@core",
}


def load_manifest(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def repo_root_from_manifest(manifest_path: Path) -> Path:
    p = manifest_path.resolve()
    if p.parent.name == "examples":
        return p.parent.parent
    if p.parent.parent.name == "plugins":
        return p.parent.parent.parent
    return p.parent.parent


def lab_vue_basename(plugin_id: str) -> str:
    slug = plugin_id.split(".")[-1]
    parts = slug.split("-")
    name = "".join(p[:1].upper() + p[1:] for p in parts)
    return f"{name}Lab.vue"


def resolve_vue_import(repo: str, root: Path, data: dict, manifest_path: Path) -> str | None:
    alias = REPO_ALIAS.get(repo)
    if not alias:
        return None
    plugin_id = data["metadata"]["id"]
    frontend_entry = data["spec"]["frontend"]["entry"]

    plugin_dir = manifest_path.parent
    local_dir = plugin_dir / "frontend"
    if local_dir.is_dir():
        local_vues = sorted(local_dir.glob("*.vue"))
        if local_vues:
            rel = local_vues[0].relative_to(root).as_posix()
            return f"{alias}/{rel}"

    fe_dir = (root / frontend_entry).parent
    named = fe_dir / lab_vue_basename(plugin_id)
    if named.is_file():
        rel = named.relative_to(root).as_posix()
        return f"{alias}/{rel}"

    vues = sorted(fe_dir.glob("*.vue"))
    if len(vues) == 1:
        rel = vues[0].relative_to(root).as_posix()
        return f"{alias}/{rel}"
    return None


def manifest_to_ref(path: Path, data: dict) -> dict:
    meta = data["metadata"]
    spec = data["spec"]
    tier = meta["compliance_tier"]
    k8s = spec.get("k8s") or {}
    ref = {
        "id": meta["id"],
        "name": meta["name"],
        "version": meta["version"],
        "repo": meta["repo"],
        "complianceTier": tier,
        "group": GROUP_MAP.get(tier, tier),
        "routePrefix": spec["frontend"]["routePrefix"],
        "frontendEntry": spec["frontend"]["entry"],
        "rulesEntry": spec["rules"]["entry"],
        "taskTypes": spec["taskTypes"],
        "namespaces": spec["namespaces"],
        "allowedChainIds": spec["allowedChainIds"],
        "manifestPath": str(path.resolve()),
    }
    if k8s.get("jobTemplate"):
        ref["jobTemplate"] = k8s["jobTemplate"]
    return ref


def generate_lab_loaders(refs: list[dict]) -> str:
    lines = [
        "import type { Component } from 'vue'",
        "",
        "export type LabLoader = () => Promise<{ default: Component }>",
        "",
        "/** Auto-generated by ci/register-plugins.py */",
        "export const LAB_PANEL_LOADERS: Record<string, LabLoader> = {",
    ]
    for ref in refs:
        pid = ref["id"]
        root = repo_root_from_manifest(Path(ref["manifestPath"]))
        data = load_manifest(Path(ref["manifestPath"]))
        imp = resolve_vue_import(ref["repo"], root, data, Path(ref["manifestPath"]))
        if imp:
            lines.append(f"  '{pid}': () => import('{imp}'),")
        else:
            lines.append(f"  // '{pid}': fallback LabView (no panel vue found)")
    lines.extend(
        [
            "}",
            "",
            "export function resolveLabLoader(pluginId: string): LabLoader | null {",
            "  return LAB_PANEL_LOADERS[pluginId] ?? null",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    plugins_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "..")
    core_root = Path(__file__).resolve().parents[1]
    out_path = core_root / "frontend-web" / "src" / "plugins" / "plugins.registry.json"
    gateway_path = core_root / "api-gateway-go" / "config" / "plugins.registry.json"
    loaders_path = core_root / "frontend-web" / "src" / "plugins" / "lab-loaders.ts"
    scheduler_registry = core_root / "control-plane-go" / "config" / "plugins.registry.json"

    refs: list[dict] = []

    mock_manifest = core_root / "examples" / "mock-plugin.manifest.yaml"
    if mock_manifest.exists():
        refs.append(manifest_to_ref(mock_manifest, load_manifest(mock_manifest)))

    for manifest in sorted(plugins_dir.rglob("plugin.manifest.yaml")):
        if "node_modules" in manifest.parts:
            continue
        data = load_manifest(manifest)
        ref = manifest_to_ref(manifest, data)
        if not any(r["id"] == ref["id"] for r in refs):
            refs.append(ref)

    payload = json.dumps(refs, indent=2, ensure_ascii=False) + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    gateway_path.parent.mkdir(parents=True, exist_ok=True)
    scheduler_registry.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(payload, encoding="utf-8")
    gateway_path.write_text(payload, encoding="utf-8")
    scheduler_registry.write_text(payload, encoding="utf-8")
    loaders_path.write_text(generate_lab_loaders(refs), encoding="utf-8")
    print(f"Registered {len(refs)} plugins -> {out_path}")
    print(f"Generated lab-loaders -> {loaders_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
